//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentHack.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentHack.Bot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option..
        /// </summary>
        internal static string MenuReportSearch {
            get {
                return ResourceManager.GetString("MenuReportSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid option..
        /// </summary>
        internal static string MenuReportSearch_NotValid {
            get {
                return ResourceManager.GetString("MenuReportSearch_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a person.
        /// </summary>
        internal static string MenuReportSearch_Report {
            get {
                return ResourceManager.GetString("MenuReportSearch_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a person.
        /// </summary>
        internal static string MenuReportSearch_Search {
            get {
                return ResourceManager.GetString("MenuReportSearch_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to identify yourself?.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not identified, the registration will be performed in anonymous mode..
        /// </summary>
        internal static string Registration_AdviseNoIdentification {
            get {
                return ResourceManager.GetString("Registration_AdviseNoIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the country where was the lost..
        /// </summary>
        internal static string Registration_Country {
            get {
                return ResourceManager.GetString("Registration_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date of the lost (mm/dd/yyyy)..
        /// </summary>
        internal static string Registration_DateOfLost {
            get {
                return ResourceManager.GetString("Registration_DateOfLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error registering the report..
        /// </summary>
        internal static string Registration_Fail {
            get {
                return ResourceManager.GetString("Registration_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the genre of the missing person..
        /// </summary>
        internal static string Registration_Genre {
            get {
                return ResourceManager.GetString("Registration_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration in progress..
        /// </summary>
        internal static string Registration_InProgress {
            get {
                return ResourceManager.GetString("Registration_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the lastname of the missing person..
        /// </summary>
        internal static string Registration_Lastname {
            get {
                return ResourceManager.GetString("Registration_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location of the lost person.
        /// </summary>
        internal static string Registration_LocationOfLost {
            get {
                return ResourceManager.GetString("Registration_LocationOfLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the missing person..
        /// </summary>
        internal static string Registration_Name {
            get {
                return ResourceManager.GetString("Registration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Registration_No {
            get {
                return ResourceManager.GetString("Registration_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid option..
        /// </summary>
        internal static string Registration_NotValid {
            get {
                return ResourceManager.GetString("Registration_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address where we will reach you with the details of the registration..
        /// </summary>
        internal static string Registration_ReportedBy {
            get {
                return ResourceManager.GetString("Registration_ReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the identifier of the report..
        /// </summary>
        internal static string Registration_ReportId {
            get {
                return ResourceManager.GetString("Registration_ReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has been successfully registered. You will receive in shortly an email with more details about the registration..
        /// </summary>
        internal static string Registration_Success {
            get {
                return ResourceManager.GetString("Registration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a photo of the missing person..
        /// </summary>
        internal static string Registration_WaitingForImage {
            get {
                return ResourceManager.GetString("Registration_WaitingForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Registration_Yes {
            get {
                return ResourceManager.GetString("Registration_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification in progress..
        /// </summary>
        internal static string Search_InProgress {
            get {
                return ResourceManager.GetString("Search_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name and lastname.
        /// </summary>
        internal static string Search_NameLastname {
            get {
                return ResourceManager.GetString("Search_NameLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No person was found..
        /// </summary>
        internal static string Search_NoItems {
            get {
                return ResourceManager.GetString("Search_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid option..
        /// </summary>
        internal static string Search_NotValid {
            get {
                return ResourceManager.GetString("Search_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By photo.
        /// </summary>
        internal static string Search_Photo {
            get {
                return ResourceManager.GetString("Search_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to search by photo or by name and lastname?.
        /// </summary>
        internal static string Search_Question {
            get {
                return ResourceManager.GetString("Search_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with the search..
        /// </summary>
        internal static string Search_VerificationError {
            get {
                return ResourceManager.GetString("Search_VerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a photo of the missing person..
        /// </summary>
        internal static string Search_WaitingForImage {
            get {
                return ResourceManager.GetString("Search_WaitingForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!, too many attempts..
        /// </summary>
        internal static string TooManyAttempts {
            get {
                return ResourceManager.GetString("TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Intelligent Hack Bot..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just say a phrase to set your preferred language..
        /// </summary>
        internal static string Welcome_TranslationMessage {
            get {
                return ResourceManager.GetString("Welcome_TranslationMessage", resourceCulture);
            }
        }
    }
}
